### ISSUE TITLE
Error managing cluster: Failure obtaining db row lock: Table 'demo-schema.QRTZ_LOCKS' doesn't exist

### ISSUE THREAD

**Issue by mond-liu** [leelance/spring-boot-all#1]
作者您好，您的例子，我把数据库放本地没问题，但配置成远程数据库，数据库一样的，却会报如题错误，不知道为何会出现如此情况，望回复

**Comment by leehaut** [comment]
@mond-liu  您好，我这个demo当时在window下面的 我的mysql设置了lower_case_table_names=1 
忽略表名大小写，
你可以在mysql配置文件/etc/my.cnf 加入lower_case_table_names=1 默认是lower_case_table_names=0 不忽略大小写

你可以通过这个查看mysql是否忽略了大小写：show variables like "%case%";

**Comment by mond-liu** [comment]
@leelance 确实是这个问题，非常感谢

**Comment by leehaut** [comment]
@mond-liu 那问题我关了
