### ISSUE TITLE
spring-boot-websocket-netty-server项目如何使用Main方法期启动

### ISSUE THREAD

**Issue by leohsu91** [leelance/spring-boot-all#14]
你好，不适用springboot:run命令，直接运行Main方法，如何启动该项目。添加了
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
 </dependency>
依赖，仍旧无效

**Comment by leehaut** [comment]
在main方法中 加入netty-server启动方法
