### ISSUE TITLE
activiti 的sql在哪里？

### ISSUE THREAD

**Issue by zhangchaoyanggit** [leelance/spring-boot-all#22]
activiti 的sql在哪里？ 没找见  还有 登陆的时候 登陆不了 走到 AuthenticatingRealm 类的 assertCredentialsMatch 方法 验证不通过   我再您的项目中的 UserRealm 类里 重写了这个方法 直接跳过了验证？ 会不会有什么影响 没用过shiro   望回复！

**Comment by leehaut** [comment]
activiti 可以直接到官网下载sql，脚本是一致的，版本一致就好了， UserRealm可以重写的，根据不同的业务进行不同处理
