### ISSUE TITLE
请问一下 我同时用这 jedis pool 和 shiro 两个东西 redis 需要怎么配置呢 

### ISSUE THREAD

**Issue by codeyung** [leelance/spring-boot-all#8]
我现在是有一个 

RedisCacheConfiguration extends CachingConfigurerSupport
{
@Bean
    public JedisConnectionFactory redisConnectionFactory() {}
@Bean
    public CacheManager cacheManager(RedisTemplate redisTemplate) {}

    @Bean
    public RedisTemplate<String, String> redisTemplate(RedisConnectionFactory factory) {}
}

ShiroConfig 该如何配置呢
因为我需要单独吧 redis 做一个 sevice 做操作 redis 

ShiroConfig 里面也需要一分配置嘛

**Comment by leehaut** [comment]
`
	@Bean(name="shrioRedisCacheManager")
	@DependsOn(value="redisTemplate")
	public ShrioRedisCacheManager redisCacheManager() {
		ShrioRedisCacheManager cacheManager = new ShrioRedisCacheManager(redisTemplate());
		
@Bean(name="securityManager")
	public DefaultWebSecurityManager securityManager() {
		DefaultWebSecurityManager manager = new DefaultWebSecurityManager();
		manager.setRealm(userRealm());
		manager.setCacheManager(redisCacheManager());
		manager.setSessionManager(defaultWebSessionManager());
		return manager;
	}

@Bean(name="redisTemplate")
	public RedisTemplate<byte[], Object> redisTemplate() {
	    RedisTemplate<byte[], Object> template = new RedisTemplate<>();
	    template.setConnectionFactory(connectionFactory());
	    return template;
	}
`

[https://github.com/leelance/spring-boot-all/blob/master/spring-boot-shiro-redis/src/main/java/com/lance/shiro/config/ShiroConfig.java](url)

**Comment by codeyung** [comment]
我试一下  谢谢
